let villages = [
    {
      name: "Red Rock",
      region: "Central",
      encyclopedia: "Home of the Red Rock warband, an elite group of warriors lead by Amelia. Named after the ubiquitous red stone formations throughout the village and surrounding areas.",
      notes: "",
      mines: "",
      refineries: "",
      buildingSites: "",
      trainingGrounds: "",
      vehicleFactory: ""
    },
    {
      name: "Caves",
      region: "Central",
      encyclopedia: "Historically remembered as the hiding place for the fledgling Ministry a century ago during the Supremacy invasion, Caves village is named after the many caves and tunnel complexes that make up the \"buildings\" of the villagers there.",
      notes: "",
      mines: "",
      refineries: "",
      buildingSites: "",
      trainingGrounds: "",
      vehicleFactory: ""
    },
    {
      name: "Foxtail",
      region: "Central",
      encyclopedia: "Oddly named considering that the Fox clan does not have a significant presence here, Foxtail village is a buffer between the Central lands and the Lowlands. Many martial heroes have hailed from Foxtail village throughout history, and popular stories are riddled with references to the beautiful place.",
      notes: "",
      mines: "",
      refineries: "",
      buildingSites: "",
      trainingGrounds: "",
      vehicleFactory: ""
    },
    {
      name: "Moss Overhang",
      region: "Central",
      encyclopedia: "Moss Overhang village is considered quaint by the typical Central lands standards. Nestled next to Academy village, it sees many people coming and going throughout the entire year. Despite being in a location to capitalize on trading routes, the people of Moss Overhang village make much of their income by hosting a bevy of taverns and inns that are often full.",
      notes: "",
      mines: "",
      refineries: "",
      buildingSites: "",
      trainingGrounds: "",
      vehicleFactory: ""
    },
    {
      name: "Peacock",
      region: "Central",
      encyclopedia: "Peacock village is not the only home to the Peacock clan, but it is the largest. Many of the Peacock clan flock to the Central lands where they can enjoy the prestige of living in the economic and political center. Although the majority of the citizens belong to the Peacock clan, most clans are also represented in Peacock village.",
      notes: "",
      mines: "",
      refineries: "",
      buildingSites: "",
      trainingGrounds: "",
      vehicleFactory: ""
    },
    {
      name: "Academy",
      region: "Central",
      encyclopedia: "Academy village is named after the Academy, the learning institution of most reknown in the Ministry. The Academy is a mass of buildings in the center of the village with districts surrounding it in concentric circles. The outer lands of Academy village are composed of verdant fields and thick forests, each of which is disappearing more and more as the institution grows.",
      notes: "",
      mines: "",
      refineries: "",
      buildingSites: "",
      trainingGrounds: "",
      vehicleFactory: ""
    },
    {
      name: "Ministry War Camp",
      region: "Central",
      encyclopedia: "Ministry War Camp village is no longer the war camp it started as; instead, it is a bustling metropolis and military center in one. Recruits into the Guard are trained here and are then sent out into the other villages in each Ministry land. Many people come to the village offering services, keeping the village constantly growing.",
      notes: "",
      mines: "",
      refineries: "",
      buildingSites: "",
      trainingGrounds: "",
      vehicleFactory: ""
    },
    {
      name: "Blue Stone River",
      region: "Central",
      encyclopedia: "The site of a major military conflict, Blue Stone River village hosts a clear river running through it. The riverbed is made up of blue polished stones, the remnats of a mountain from which the river flows. The villagers strictly forbid anyone from taking a stone from the river, and levy a heavy punishment for those that disobey the tradition.",
      notes: "",
      mines: "",
      refineries: "",
      buildingSites: "",
      trainingGrounds: "",
      vehicleFactory: ""
    },
    {
      name: "Dry Bed Creek",
      region: "Central",
      encyclopedia: "Known for their trade in elegant and exotic furs.",
      notes: "",
      mines: "",
      refineries: "",
      buildingSites: "",
      trainingGrounds: "",
      vehicleFactory: ""
    },
    {
      name: "Lion Throne",
      region: "Central",
      encyclopedia: "Lion Throne village is the seat of Ministry power. From here, the Highest Minister rules the lands and pronounces judgment on them. Civilian dignataries and their retinue are frequently seen among the military leaders and officer corp. The center of politics, the Lion Throne village is where deals are made with a lasting impact on the Ministry.",
      notes: "",
      mines: "",
      refineries: "",
      buildingSites: "",
      trainingGrounds: "",
      vehicleFactory: ""
    },
    {
      name: "Ministry Outpost",
      region: "Badlands",
      encyclopedia: "Considered a punishment assignment among the Guard, the Ministry Outpost village is the only military presence in the Badlands.",
      notes: "",
      mines: "",
      refineries: "",
      buildingSites: "",
      trainingGrounds: "",
      vehicleFactory: ""
    },
    {
      name: "Barren Lands",
      region: "Badlands",
      encyclopedia: "The Barren Lands are devoid of all human life but for the occasional nomads.",
      notes: "",
      mines: "",
      refineries: "",
      buildingSites: "",
      trainingGrounds: "",
      vehicleFactory: ""
    },
    {
      name: "Scalded Lands",
      region: "Badlands",
      encyclopedia: "The Scalded Lands are heated by two sources: the ever-present sun and the volcanic eruptions throughout. Hardly livable, even the Nomads barely venture into it.",
      notes: "",
      mines: "",
      refineries: "",
      buildingSites: "",
      trainingGrounds: "",
      vehicleFactory: ""
    },
    {
      name: "Nomad Lands",
      region: "Badlands",
      encyclopedia: "The Nomad Lands village is the site of a centuries-old waystop for an ancient nomadic people. Now, for the most part, the villagers stay rooted like any other village, though there are a few a few tribes that wander in the Badlands, seeking to remember the old ways.",
      notes: "",
      mines: "",
      refineries: "",
      buildingSites: "",
      trainingGrounds: "",
      vehicleFactory: ""
    },
    {
      name: "Salted Lands",
      region: "Badlands",
      encyclopedia: "Many myths exist about the origin of the Salted Lands, including the site of an ancient sea, and the salting from a destructive army. The truth may never be known as it has been lost to the ages.",
      notes: "",
      mines: "",
      refineries: "",
      buildingSites: "",
      trainingGrounds: "",
      vehicleFactory: ""
    },
    {
      name: "Frozen Lands",
      region: "Badlands",
      encyclopedia: "The Frozen Lands exist on an icy tundra with a constant biting wind. Despite the inhospitable terrain, the nomads often spend the warmer months in the Frozen Lands, hunting the plentiful game there.",
      notes: "",
      mines: "",
      refineries: "",
      buildingSites: "",
      trainingGrounds: "",
      vehicleFactory: ""
    },
    {
      name: "Obsidian Legion",
      region: "Badlands",
      encyclopedia: "The Obsidian Legion village was founded by the famed Obsidian Legion several generations ago, and the militaristic tradition continues on through today. Most of the Elite Guard are made up of soldiers from the Obsidian Legion village, as the difficult environment and upbringing force them to be hardy warriors in order to survive.",
      notes: "",
      mines: "",
      refineries: "",
      buildingSites: "",
      trainingGrounds: "",
      vehicleFactory: ""
    },
    {
      name: "Oasis",
      region: "Badlands",
      encyclopedia: "Oasis village is a plush area in the middle of the Badlands. Despite the temperate living conditions, the nomads only stay for short periods, and forbid any permanent settlement. They fear that the Oasis village would be subsumed if not left mostly alone. Bathing in the plentiful springs is part of the nomads' religions, and while they allow outsiders to do so, they consider any desecration of the springs to be an act of war.",
      notes: "",
      mines: "",
      refineries: "",
      buildingSites: "",
      trainingGrounds: "",
      vehicleFactory: ""
    },
    {
      name: "Meteor Fall",
      region: "Badlands",
      encyclopedia: "The nomads generally avoid Meteor Fall village as it and the surrounding lands suffer from a barrage of meteorites. No one knows why the land is such a magnet for meteor showers and the meteorites that make it through, but many religions have incorporated the land into scripture as the place of suffering for the unworthy.",
      notes: "",
      mines: "",
      refineries: "",
      buildingSites: "",
      trainingGrounds: "",
      vehicleFactory: ""
    },
    {
      name: "Acid Lands",
      region: "Badlands",
      encyclopedia: "Any water that flows into the Acid Lands soon mixes with the potent minerals and becomes acidic. If they must cross it, the Nomads do so at a dead gallop with their own clean water in ready supply.",
      notes: "",
      mines: "",
      refineries: "",
      buildingSites: "",
      trainingGrounds: "",
      vehicleFactory: ""
    },
    {
      name: "Lookout Pass",
      region: "Dusty Mountains",
      encyclopedia: "Lookout Pass village stands sentinel at the Dusty Mountains entrance. The scouts stationed there can see an approaching force from miles away, and a small army can delay invaders using the small width of the pass.",
      notes: "",
      mines: "",
      refineries: "",
      buildingSites: "",
      trainingGrounds: "",
      vehicleFactory: ""
    },
    {
      name: "High Ridge",
      region: "Dusty Mountains",
      encyclopedia: "High Ridge village not only stands atop the highest plateau, it also extends down the sheer cliff face where villagers have carved their houses into it.",
      notes: "",
      mines: "",
      refineries: "",
      buildingSites: "",
      trainingGrounds: "",
      vehicleFactory: ""
    },
    {
      name: "Penal Mines",
      region: "Dusty Mountains",
      encyclopedia: "A prison assignment for political enemies and dissidents, the Penal Mines now host more actual criminals than it did under previous rulers.",
      notes: "",
      mines: "",
      refineries: "",
      buildingSites: "",
      trainingGrounds: "",
      vehicleFactory: ""
    },
    {
      name: "Old Stone Quarry",
      region: "Dusty Mountains",
      encyclopedia: "Old Stone Quarry village is a mining operation that brings necessary building materials to the rest of the Ministry lands.",
      notes: "",
      mines: "",
      refineries: "",
      buildingSites: "",
      trainingGrounds: "",
      vehicleFactory: ""
    },
    {
      name: "Aerie Preserve",
      region: "Dusty Mountains",
      encyclopedia: "Aerie Preserve village welcomes all who respect the tenet of not hunting the birds that live there. Considered a retreat for the bird-oriented clans, it was originally founded as a refuge for the animals that take to the air.",
      notes: "",
      mines: "",
      refineries: "",
      buildingSites: "",
      trainingGrounds: "",
      vehicleFactory: ""
    },
    {
      name: "Dragon Peak",
      region: "Dusty Mountains",
      encyclopedia: "Generations ago, the Jackal clan split over a feud with half of them settling in Dragon Peak. The feud has long been forgotten and peace restored, with Dragon Peak hosting similar numbers of the Jackal clan as the Jackal village in the Lowlands.",
      notes: "",
      mines: "",
      refineries: "",
      buildingSites: "",
      trainingGrounds: "",
      vehicleFactory: ""
    },
    {
      name: "Warrens",
      region: "Dusty Mountains",
      encyclopedia: "Holes bored into holes bored into holes, the Warrens village is home to many a miscreant that needs a place to hide. Largely lawless, the village sees a huge turnover in population in very short time.",
      notes: "",
      mines: "",
      refineries: "",
      buildingSites: "",
      trainingGrounds: "",
      vehicleFactory: ""
    },
    {
      name: "Black Drop Caves",
      region: "Dusty Mountains",
      encyclopedia: "Black Drop Cave village is a system of caves housing hundreds of people, mostly from the Bat clan. Fresh water flows along natural canals, making it an ideal choice of village for those in the Dusty Mountains.",
      notes: "",
      mines: "",
      refineries: "",
      buildingSites: "",
      trainingGrounds: "",
      vehicleFactory: ""
    },
    {
      name: "Springs Caldera",
      region: "Dusty Mountains",
      encyclopedia: "Springs Caldera is a largely inactive vent of Springs Volcano. Water pools up from a natural spring, which is heated by the blazing land around it. No village exists here, but wanderers do pass through from time to time.",
      notes: "",
      mines: "",
      refineries: "",
      buildingSites: "",
      trainingGrounds: "",
      vehicleFactory: ""
    },
    {
      name: "Springs Volcano",
      region: "Dusty Mountains",
      encyclopedia: "Bordering the Scalded Lands of the Badlands, Springs Volcano is a semi-active volcano, typically erupting every fifty years or so. No village has ever been built around it, and the volcano does not see many visitors.",
      notes: "",
      mines: "",
      refineries: "",
      buildingSites: "",
      trainingGrounds: "",
      vehicleFactory: ""
    },
    {
      name: "Troll Haunt",
      region: "Lowlands",
      encyclopedia: "Bordering Foxtail village, Troll Haunt village starts the gradual descent into the Lowlands. Named for the wailing sound caused by the wind blowing past odd rock formations. The mythical race of trolls has never been sighted, but some of the common people still devoutly believe that trolls once lived in the area. ",
      notes: "",
      mines: "",
      refineries: "",
      buildingSites: "",
      trainingGrounds: "",
      vehicleFactory: ""
    },
    {
      name: "Red Herd",
      region: "Lowlands",
      encyclopedia: "Red Herd village has more livestock than people, and it has many people. The thriving trade makes it an attractive place to many of the poorer villages in the Ministry.",
      notes: "",
      mines: "",
      refineries: "",
      buildingSites: "",
      trainingGrounds: "",
      vehicleFactory: ""
    },
    {
      name: "Lion Farm",
      region: "Lowlands",
      encyclopedia: "Lion Farm village is a state-run farming village which supplies food to the Guard.",
      notes: "",
      mines: "",
      refineries: "",
      buildingSites: "",
      trainingGrounds: "",
      vehicleFactory: ""
    },
    {
      name: "Blue Ice Hole",
      region: "Lowlands",
      encyclopedia: "A quiet fishing village, Blue Ice Hole village has many rivers and streams running through, and many sizeable lakes.",
      notes: "",
      mines: "",
      refineries: "",
      buildingSites: "",
      trainingGrounds: "",
      vehicleFactory: ""
    },
    {
      name: "Hyena",
      region: "Lowlands",
      encyclopedia: "The Hyena clan's main population resides in the Hyena village, a choice spot of land bordering Red Herd village. Despite their reputation, the Hyena clan raises livestock there instead of stealing from their neighbors.",
      notes: "",
      mines: "",
      refineries: "",
      buildingSites: "",
      trainingGrounds: "",
      vehicleFactory: ""
    },
    {
      name: "Jackal",
      region: "Lowlands",
      encyclopedia: "The Jackal clan is largely split between Jackal village and Dragon Peak village, with friendly coming and going between them. Suffering from as poor a reputation as the Hyena clan, the people of the Jackal clan work hard to show their industry instead of their supposed theft.",
      notes: "",
      mines: "",
      refineries: "",
      buildingSites: "",
      trainingGrounds: "",
      vehicleFactory: ""
    },
    {
      name: "The Pits",
      region: "Lowlands",
      encyclopedia: "Bordering Troll Haunt village, The Pits is a land without a village, as the yawning pits in the land are constant and difficult to build around. For those that have studied the place, it seems that no new pits have formed in living memory, despite the legend that The Pits is constantly shifting and closing old pits to make new ones.",
      notes: "",
      mines: "",
      refineries: "",
      buildingSites: "",
      trainingGrounds: "",
      vehicleFactory: ""
    },
    {
      name: "Golden Wheat",
      region: "Lowlands",
      encyclopedia: "An agricultural village, Golden Wheat village is integral to the food supply of the entire Ministry.",
      notes: "",
      mines: "",
      refineries: "",
      buildingSites: "",
      trainingGrounds: "",
      vehicleFactory: ""
    },
    {
      name: "Rocky Falls",
      region: "Lowlands",
      encyclopedia: "Bordering Blue Ice Hole village, the rivers from there lead to waterfalls in Rocky Falls village. The many water sources make the village an ideal place for raising crops and herds.",
      notes: "",
      mines: "",
      refineries: "",
      buildingSites: "",
      trainingGrounds: "",
      vehicleFactory: ""
    },
    {
      name: "Hill Marsh",
      region: "Lowlands",
      encyclopedia: "Water from Blue Ice Hole and Rocky Falls villages seeps into the Hill Marsh, creating a humid swamp. No official village exists there, but many people down on their luck pitch their tents here and try to make a life out of it.",
      notes: "",
      mines: "",
      refineries: "",
      buildingSites: "",
      trainingGrounds: "",
      vehicleFactory: ""
    },
    {
      name: "Ministry Garrison",
      region: "Borderlands",
      encyclopedia: "The Ministry Garrison is constantly manned by the Guard, keeping a military presence available should any incursion be made into the Ministry.",
      notes: "",
      mines: "",
      refineries: "",
      buildingSites: "",
      trainingGrounds: "",
      vehicleFactory: ""
    },
    {
      name: "Guard Post",
      region: "Borderlands",
      encyclopedia: "The Guard Post village is a smaller version of the Ministry Garrison. The soldiers from each village attract a sizeable following of people peddling their business to meet the soldiers' needs.",
      notes: "",
      mines: "",
      refineries: "",
      buildingSites: "",
      trainingGrounds: "",
      vehicleFactory: ""
    },
    {
      name: "Supremacy",
      region: "Borderlands",
      encyclopedia: "The Supremacy village was built in the Ministry lands during a period of uneasy peace. Border skirmishes between the armies flare up now and again, but the civilians have friendly trade with one another and are largely apathetic to the occasional news of fighting.",
      notes: "",
      mines: "",
      refineries: "",
      buildingSites: "",
      trainingGrounds: "",
      vehicleFactory: ""
    },
    {
      name: "Commonwealth",
      region: "Borderlands",
      encyclopedia: "The Commonwealth village hosts the Commonwealth embassy. The diplomats there have petitioned for an embassy in the Central lands, but without progress. Unlike the Supremacy, there aren't any border skirmishes with the Commonwealth. Despite that fact, each nation keeps a large military presence on each side of the border.",
      notes: "",
      mines: "",
      refineries: "",
      buildingSites: "",
      trainingGrounds: "",
      vehicleFactory: ""
    },
    {
      name: "Trading Post",
      region: "Borderlands",
      encyclopedia: "Trading Post village is exactly what it sounds like. The diminuitive village swells in size when the army marches through, and then shrinks until they return.",
      notes: "",
      mines: "",
      refineries: "",
      buildingSites: "",
      trainingGrounds: "",
      vehicleFactory: ""
    },
    {
      name: "Eagle's Nest",
      region: "Borderlands",
      encyclopedia: "Eagle's Nest village is the highest point in the Borderlands with a view into both the Commonwealth and Supremacy lands. A permanent Guard presence is stationed there.",
      notes: "",
      mines: "",
      refineries: "",
      buildingSites: "",
      trainingGrounds: "",
      vehicleFactory: ""
    },
    {
      name: "Gray Temple",
      region: "Borderlands",
      encyclopedia: "Gray Temple village is the site of a pilgramage for the people of the Ministry. Destroyed long ago, the famous Gray Temple was rebuilt after a protracted war with the Supremacy.",
      notes: "",
      mines: "",
      refineries: "",
      buildingSites: "",
      trainingGrounds: "",
      vehicleFactory: ""
    },
    {
      name: "Elephant",
      region: "Borderlands",
      encyclopedia: "Place holder",
      notes: "",
      mines: "",
      refineries: "",
      buildingSites: "",
      trainingGrounds: "",
      vehicleFactory: ""
    },
    {
      name: "Ancient Ruins",
      region: "Borderlands",
      encyclopedia: "Place holder",
      notes: "",
      mines: "",
      refineries: "",
      buildingSites: "",
      trainingGrounds: "",
      vehicleFactory: ""
    },
    {
      name: "Blade Trail",
      region: "Borderlands",
      encyclopedia: "Place holder",
      notes: "",
      mines: "",
      refineries: "",
      buildingSites: "",
      trainingGrounds: "",
      vehicleFactory: ""
    },
    {
      name: "Cinnamon Plains",
      region: "Hinterlands",
      encyclopedia: "Place holder",
      notes: "",
      mines: "",
      refineries: "",
      buildingSites: "",
      trainingGrounds: "",
      vehicleFactory: ""
    },
    {
      name: "Independence Battlefield",
      region: "Hinterlands",
      encyclopedia: "Place holder",
      notes: "",
      mines: "",
      refineries: "",
      buildingSites: "",
      trainingGrounds: "",
      vehicleFactory: ""
    },
    {
      name: "Rock Shelter",
      region: "Hinterlands",
      encyclopedia: "Place holder",
      notes: "",
      mines: "",
      refineries: "",
      buildingSites: "",
      trainingGrounds: "",
      vehicleFactory: ""
    },
    {
      name: "Old Preserve",
      region: "Hinterlands",
      encyclopedia: "Place holder",
      notes: "",
      mines: "",
      refineries: "",
      buildingSites: "",
      trainingGrounds: "",
      vehicleFactory: ""
    },
    {
      name: "Clay Bridge",
      region: "Hinterlands",
      encyclopedia: "Place holder",
      notes: "",
      mines: "",
      refineries: "",
      buildingSites: "",
      trainingGrounds: "",
      vehicleFactory: ""
    },
    {
      name: "Gray Arena",
      region: "Hinterlands",
      encyclopedia: "Place holder",
      notes: "",
      mines: "",
      refineries: "",
      buildingSites: "",
      trainingGrounds: "",
      vehicleFactory: ""
    },
    {
      name: "Wolf",
      region: "Hinterlands",
      encyclopedia: "Place holder",
      notes: "",
      mines: "",
      refineries: "",
      buildingSites: "",
      trainingGrounds: "",
      vehicleFactory: ""
    },
    {
      name: "Vulture Aviary",
      region: "Hinterlands",
      encyclopedia: "Place holder",
      notes: "",
      mines: "",
      refineries: "",
      buildingSites: "",
      trainingGrounds: "",
      vehicleFactory: ""
    },
    {
      name: "Sand Basin",
      region: "Hinterlands",
      encyclopedia: "Place holder",
      notes: "",
      mines: "",
      refineries: "",
      buildingSites: "",
      trainingGrounds: "",
      vehicleFactory: ""
    },
    {
      name: "Salt Flat",
      region: "Hinterlands",
      encyclopedia: "Place holder",
      notes: "",
      mines: "",
      refineries: "",
      buildingSites: "",
      trainingGrounds: "",
      vehicleFactory: ""
    },
    {
      name: "Turtle Archipelago",
      region: "Floodplains",
      encyclopedia: "Place holder",
      notes: "",
      mines: "",
      refineries: "",
      buildingSites: "",
      trainingGrounds: "",
      vehicleFactory: ""
    },
    {
      name: "Bright Star",
      region: "Floodplains",
      encyclopedia: "Place holder",
      notes: "",
      mines: "",
      refineries: "",
      buildingSites: "",
      trainingGrounds: "",
      vehicleFactory: ""
    },
    {
      name: "New Preserve",
      region: "Floodplains",
      encyclopedia: "Place holder",
      notes: "",
      mines: "",
      refineries: "",
      buildingSites: "",
      trainingGrounds: "",
      vehicleFactory: ""
    },
    {
      name: "Ginger Hills",
      region: "Floodplains",
      encyclopedia: "Place holder",
      notes: "",
      mines: "",
      refineries: "",
      buildingSites: "",
      trainingGrounds: "",
      vehicleFactory: ""
    },
    {
      name: "Granite Lodge",
      region: "Floodplains",
      encyclopedia: "Place holder",
      notes: "",
      mines: "",
      refineries: "",
      buildingSites: "",
      trainingGrounds: "",
      vehicleFactory: ""
    },
    {
      name: "Hard Claw",
      region: "Floodplains",
      encyclopedia: "Place holder",
      notes: "",
      mines: "",
      refineries: "",
      buildingSites: "",
      trainingGrounds: "",
      vehicleFactory: ""
    },
    {
      name: "The Flats",
      region: "Floodplains",
      encyclopedia: "Place holder",
      notes: "",
      mines: "",
      refineries: "",
      buildingSites: "",
      trainingGrounds: "",
      vehicleFactory: ""
    },
    {
      name: "Capped Bay",
      region: "Floodplains",
      encyclopedia: "Place holder",
      notes: "",
      mines: "",
      refineries: "",
      buildingSites: "",
      trainingGrounds: "",
      vehicleFactory: ""
    },
    {
      name: "Rainy Beach",
      region: "Floodplains",
      encyclopedia: "Place holder",
      notes: "",
      mines: "",
      refineries: "",
      buildingSites: "",
      trainingGrounds: "",
      vehicleFactory: ""
    },
    {
      name: "Barnacle Beach",
      region: "Floodplains",
      encyclopedia: "Place holder",
      notes: "",
      mines: "",
      refineries: "",
      buildingSites: "",
      trainingGrounds: "",
      vehicleFactory: ""
    },
    {
      name: "Rock Tower",
      region: "Wetlands",
      encyclopedia: "Place holder",
      notes: "",
      mines: "",
      refineries: "",
      buildingSites: "",
      trainingGrounds: "",
      vehicleFactory: ""
    },
    {
      name: "Salmon Rapids",
      region: "Wetlands",
      encyclopedia: "Place holder",
      notes: "",
      mines: "",
      refineries: "",
      buildingSites: "",
      trainingGrounds: "",
      vehicleFactory: ""
    },
    {
      name: "Blue Marsh",
      region: "Wetlands",
      encyclopedia: "Place holder",
      notes: "",
      mines: "",
      refineries: "",
      buildingSites: "",
      trainingGrounds: "",
      vehicleFactory: ""
    },
    {
      name: "Salmon Stream",
      region: "Wetlands",
      encyclopedia: "Place holder",
      notes: "",
      mines: "",
      refineries: "",
      buildingSites: "",
      trainingGrounds: "",
      vehicleFactory: ""
    },
    {
      name: "Crystal Grotto",
      region: "Wetlands",
      encyclopedia: "Place holder",
      notes: "",
      mines: "",
      refineries: "",
      buildingSites: "",
      trainingGrounds: "",
      vehicleFactory: ""
    },
    {
      name: "Quiet Bayou",
      region: "Wetlands",
      encyclopedia: "Place holder",
      notes: "",
      mines: "",
      refineries: "",
      buildingSites: "",
      trainingGrounds: "",
      vehicleFactory: ""
    },
    {
      name: "Crocodile",
      region: "Wetlands",
      encyclopedia: "Place holder",
      notes: "",
      mines: "",
      refineries: "",
      buildingSites: "",
      trainingGrounds: "",
      vehicleFactory: ""
    },
    {
      name: "Sage Swamp",
      region: "Wetlands",
      encyclopedia: "Place holder",
      notes: "",
      mines: "",
      refineries: "",
      buildingSites: "",
      trainingGrounds: "",
      vehicleFactory: ""
    },
    {
      name: "Sulfur Mines",
      region: "Wetlands",
      encyclopedia: "The mines yield ores of several varieties; the village is named after the odorous pits in the surrounding areas. The mines are owned and run by Ayesha, who pays extremely well to keep workers from leaving the undesirable land.",
      notes: "",
      mines: "",
      refineries: "",
      buildingSites: "",
      trainingGrounds: "",
      vehicleFactory: ""
    },
    {
      name: "Painted Bog",
      region: "Wetlands",
      encyclopedia: "Place holder",
      notes: "",
      mines: "",
      refineries: "",
      buildingSites: "",
      trainingGrounds: "",
      vehicleFactory: ""
    },
    {
      name: "High Bluffs",
      region: "Highlands",
      encyclopedia: "Place holder",
      notes: "",
      mines: "",
      refineries: "",
      buildingSites: "",
      trainingGrounds: "",
      vehicleFactory: ""
    },
    {
      name: "Burnt Plains",
      region: "Highlands",
      encyclopedia: "Place holder",
      notes: "",
      mines: "",
      refineries: "",
      buildingSites: "",
      trainingGrounds: "",
      vehicleFactory: ""
    },
    {
      name: "Craggy Slopes",
      region: "Highlands",
      encyclopedia: "Place holder",
      notes: "",
      mines: "",
      refineries: "",
      buildingSites: "",
      trainingGrounds: "",
      vehicleFactory: ""
    },
    {
      name: "Arid Peak",
      region: "Highlands",
      encyclopedia: "Place holder",
      notes: "",
      mines: "",
      refineries: "",
      buildingSites: "",
      trainingGrounds: "",
      vehicleFactory: ""
    },
    {
      name: "Low Canyon",
      region: "Highlands",
      encyclopedia: "Place holder",
      notes: "",
      mines: "",
      refineries: "",
      buildingSites: "",
      trainingGrounds: "",
      vehicleFactory: ""
    },
    {
      name: "Bright Caverns",
      region: "Highlands",
      encyclopedia: "Place holder",
      notes: "",
      mines: "",
      refineries: "",
      buildingSites: "",
      trainingGrounds: "",
      vehicleFactory: ""
    },
    {
      name: "Folded Chasm",
      region: "Highlands",
      encyclopedia: "Place holder",
      notes: "",
      mines: "",
      refineries: "",
      buildingSites: "",
      trainingGrounds: "",
      vehicleFactory: ""
    },
    {
      name: "War Camp",
      region: "Highlands",
      encyclopedia: "Place holder",
      notes: "",
      mines: "",
      refineries: "",
      buildingSites: "",
      trainingGrounds: "",
      vehicleFactory: ""
    },
    {
      name: "Nine Bridges",
      region: "Highlands",
      encyclopedia: "Place holder",
      notes: "",
      mines: "",
      refineries: "",
      buildingSites: "",
      trainingGrounds: "",
      vehicleFactory: ""
    },
    {
      name: "High Loft",
      region: "Highlands",
      encyclopedia: "Place holder",
      notes: "",
      mines: "",
      refineries: "",
      buildingSites: "",
      trainingGrounds: "",
      vehicleFactory: ""
    },
    {
      name: "Sloping Fields",
      region: "Northlands",
      encyclopedia: "Place holder",
      notes: "",
      mines: "",
      refineries: "",
      buildingSites: "",
      trainingGrounds: "",
      vehicleFactory: ""
    },
    {
      name: "Ice Flow",
      region: "Northlands",
      encyclopedia: "Place holder",
      notes: "",
      mines: "",
      refineries: "",
      buildingSites: "",
      trainingGrounds: "",
      vehicleFactory: ""
    },
    {
      name: "Glacier Peak",
      region: "Northlands",
      encyclopedia: "Place holder",
      notes: "",
      mines: "",
      refineries: "",
      buildingSites: "",
      trainingGrounds: "",
      vehicleFactory: ""
    },
    {
      name: "Snow Path",
      region: "Northlands",
      encyclopedia: "Place holder",
      notes: "",
      mines: "",
      refineries: "",
      buildingSites: "",
      trainingGrounds: "",
      vehicleFactory: ""
    },
    {
      name: "Bear",
      region: "Northlands",
      encyclopedia: "Place holder",
      notes: "",
      mines: "",
      refineries: "",
      buildingSites: "",
      trainingGrounds: "",
      vehicleFactory: ""
    },
    {
      name: "Rabbit",
      region: "Northlands",
      encyclopedia: "Place holder",
      notes: "",
      mines: "",
      refineries: "",
      buildingSites: "",
      trainingGrounds: "",
      vehicleFactory: ""
    },
    {
      name: "Frostgroves",
      region: "Northlands",
      encyclopedia: "Place holder",
      notes: "",
      mines: "",
      refineries: "",
      buildingSites: "",
      trainingGrounds: "",
      vehicleFactory: ""
    },
    {
      name: "Cliffhold",
      region: "Northlands",
      encyclopedia: "Place holder",
      notes: "",
      mines: "",
      refineries: "",
      buildingSites: "",
      trainingGrounds: "",
      vehicleFactory: ""
    },
    {
      name: "North Fjords",
      region: "Northlands",
      encyclopedia: "Place holder",
      notes: "",
      mines: "",
      refineries: "",
      buildingSites: "",
      trainingGrounds: "",
      vehicleFactory: ""
    },
    {
      name: "Sword Hilt",
      region: "Northlands",
      encyclopedia: "Place holder",
      notes: "",
      mines: "",
      refineries: "",
      buildingSites: "",
      trainingGrounds: "",
      vehicleFactory: ""
    },
    {
      name: "The Craters",
      region: "Farmlands",
      encyclopedia: "Place holder",
      notes: "",
      mines: "",
      refineries: "",
      buildingSites: "",
      trainingGrounds: "",
      vehicleFactory: ""
    },
    {
      name: "Horse",
      region: "Farmlands",
      encyclopedia: "Place holder",
      notes: "",
      mines: "",
      refineries: "",
      buildingSites: "",
      trainingGrounds: "",
      vehicleFactory: ""
    },
    {
      name: "Delta",
      region: "Farmlands",
      encyclopedia: "Place holder",
      notes: "",
      mines: "",
      refineries: "",
      buildingSites: "",
      trainingGrounds: "",
      vehicleFactory: ""
    },
    {
      name: "Chicken",
      region: "Farmlands",
      encyclopedia: "Place holder",
      notes: "",
      mines: "",
      refineries: "",
      buildingSites: "",
      trainingGrounds: "",
      vehicleFactory: ""
    },
    {
      name: "Raging River",
      region: "Farmlands",
      encyclopedia: "Place holder",
      notes: "",
      mines: "",
      refineries: "",
      buildingSites: "",
      trainingGrounds: "",
      vehicleFactory: ""
    },
    {
      name: "Fresh River",
      region: "Farmlands",
      encyclopedia: "Place holder",
      notes: "",
      mines: "",
      refineries: "",
      buildingSites: "",
      trainingGrounds: "",
      vehicleFactory: ""
    },
    {
      name: "Stacked Stone",
      region: "Farmlands",
      encyclopedia: "Despite being a typical agricultural village, Stacked Stone village produces a disproportionate amount of soldiers compared to most villages, even outside the Farmlands. The recruits from the village are reknowned for their immense strength, which is cultivated by a childhood spent laboring on the land.",
      notes: "",
      mines: "",
      refineries: "",
      buildingSites: "",
      trainingGrounds: "",
      vehicleFactory: ""
    },
    {
      name: "Fallen Tree",
      region: "Farmlands",
      encyclopedia: "Place holder",
      notes: "",
      mines: "",
      refineries: "",
      buildingSites: "",
      trainingGrounds: "",
      vehicleFactory: ""
    },
    {
      name: "Granite Falls",
      region: "Farmlands",
      encyclopedia: "Place holder",
      notes: "",
      mines: "",
      refineries: "",
      buildingSites: "",
      trainingGrounds: "",
      vehicleFactory: ""
    },
    {
      name: "Festival",
      region: "Farmlands",
      encyclopedia: "Place holder",
      notes: "",
      mines: "",
      refineries: "",
      buildingSites: "",
      trainingGrounds: "",
      vehicleFactory: ""
    },
    {
      name: "The Trenches",
      region: "Heartlands",
      encyclopedia: "Place holder",
      notes: "",
      mines: "",
      refineries: "",
      buildingSites: "",
      trainingGrounds: "",
      vehicleFactory: ""
    },
    {
      name: "Wooded Hills",
      region: "Heartlands",
      encyclopedia: "Place holder",
      notes: "",
      mines: "",
      refineries: "",
      buildingSites: "",
      trainingGrounds: "",
      vehicleFactory: ""
    },
    {
      name: "Pearl",
      region: "Heartlands",
      encyclopedia: "Place holder",
      notes: "",
      mines: "",
      refineries: "",
      buildingSites: "",
      trainingGrounds: "",
      vehicleFactory: ""
    },
    {
      name: "The Docks",
      region: "Heartlands",
      encyclopedia: "Place holder",
      notes: "",
      mines: "",
      refineries: "",
      buildingSites: "",
      trainingGrounds: "",
      vehicleFactory: ""
    },
    {
      name: "The Shallows",
      region: "Heartlands",
      encyclopedia: "Place holder",
      notes: "",
      mines: "",
      refineries: "",
      buildingSites: "",
      trainingGrounds: "",
      vehicleFactory: ""
    },
    {
      name: "Storm Gulch",
      region: "Heartlands",
      encyclopedia: "Place holder",
      notes: "",
      mines: "",
      refineries: "",
      buildingSites: "",
      trainingGrounds: "",
      vehicleFactory: ""
    },
    {
      name: "Sheltered",
      region: "Heartlands",
      encyclopedia: "Place holder",
      notes: "",
      mines: "",
      refineries: "",
      buildingSites: "",
      trainingGrounds: "",
      vehicleFactory: ""
    },
    {
      name: "Brush River",
      region: "Heartlands",
      encyclopedia: "Place holder",
      notes: "",
      mines: "",
      refineries: "",
      buildingSites: "",
      trainingGrounds: "",
      vehicleFactory: ""
    },
    {
      name: "Storm Channel",
      region: "Heartlands",
      encyclopedia: "Place holder",
      notes: "",
      mines: "",
      refineries: "",
      buildingSites: "",
      trainingGrounds: "",
      vehicleFactory: ""
    },
    {
      name: "Guard Training",
      region: "Heartlands",
      encyclopedia: "Place holder",
      notes: "",
      mines: "",
      refineries: "",
      buildingSites: "",
      trainingGrounds: "",
      vehicleFactory: ""
    },
    {
      name: "Gated Wall",
      region: "Frostlands",
      encyclopedia: "Place holder",
      notes: "",
      mines: "",
      refineries: "",
      buildingSites: "",
      trainingGrounds: "",
      vehicleFactory: ""
    },
    {
      name: "Haunted Spire",
      region: "Frostlands",
      encyclopedia: "Place holder",
      notes: "",
      mines: "",
      refineries: "",
      buildingSites: "",
      trainingGrounds: "",
      vehicleFactory: ""
    },
    {
      name: "Open Market",
      region: "Frostlands",
      encyclopedia: "Place holder",
      notes: "",
      mines: "",
      refineries: "",
      buildingSites: "",
      trainingGrounds: "",
      vehicleFactory: ""
    },
    {
      name: "The Hatchery",
      region: "Frostlands",
      encyclopedia: "Place holder",
      notes: "",
      mines: "",
      refineries: "",
      buildingSites: "",
      trainingGrounds: "",
      vehicleFactory: ""
    },
    {
      name: "Flooded River",
      region: "Frostlands",
      encyclopedia: "Place holder",
      notes: "",
      mines: "",
      refineries: "",
      buildingSites: "",
      trainingGrounds: "",
      vehicleFactory: ""
    },
    {
      name: "Foothils",
      region: "Frostlands",
      encyclopedia: "Place holder",
      notes: "",
      mines: "",
      refineries: "",
      buildingSites: "",
      trainingGrounds: "",
      vehicleFactory: ""
    },
    {
      name: "Guard Fort",
      region: "Frostlands",
      encyclopedia: "Place holder",
      notes: "",
      mines: "",
      refineries: "",
      buildingSites: "",
      trainingGrounds: "",
      vehicleFactory: ""
    },
    {
      name: "Triumph",
      region: "Frostlands",
      encyclopedia: "Formerly the Green Grove village, Triumph was the site of a failed uprising put down by Logan. Upon his victory, Logan renamed the village, much to the dismay of the survivors. Despite their defeat, the villagers still gather and talk of taking down the hated Minister of the Frostlands.",
      notes: "",
      mines: "",
      refineries: "",
      buildingSites: "",
      trainingGrounds: "",
      vehicleFactory: ""
    },
    {
      name: "Dragana Gap",
      region: "Frostlands",
      encyclopedia: "Place holder",
      notes: "",
      mines: "",
      refineries: "",
      buildingSites: "",
      trainingGrounds: "",
      vehicleFactory: ""
    },
    {
      name: "Amahle Peak",
      region: "Frostlands",
      encyclopedia: "Place holder",
      notes: "",
      mines: "",
      refineries: "",
      buildingSites: "",
      trainingGrounds: "",
      vehicleFactory: ""
    },
    {
      name: "New Green Grove",
      region: "Gravelands",
      encyclopedia: "Recently founded by Nian Zhen, New Green Grove village is the site of a recent battle in which the Rebel lions were perilously close to be utterly destroyed. The Ministry was defeated spectacularly, but now New Green Grove village is no longer the secret safe haven it used to be.",
      notes: "",
      mines: "",
      refineries: "",
      buildingSites: "",
      trainingGrounds: "",
      vehicleFactory: ""
    },
    {
      name: "The Needles",
      region: "Gravelands",
      encyclopedia: "The people of the Needles joke with dark humor that they don't live in the Gravelands, but the Dying Lands. The village is almost entirely sustained by importing food; the food grown there is weak and typically dies on the vine. The people raised in the Needles are known to be hardy and independent warriors, and tend to make most of their living offering their services as mercenaries. The Needles village is so named because of the broken spines that jut up from the ground. No one living knows the true explanation for them, although rumors and legends abound.",
      notes: "",
      mines: "",
      refineries: "",
      buildingSites: "",
      trainingGrounds: "",
      vehicleFactory: ""
    },
    {
      name: "Raptor Heights",
      region: "Gravelands",
      encyclopedia: "Place holder",
      notes: "",
      mines: "",
      refineries: "",
      buildingSites: "",
      trainingGrounds: "",
      vehicleFactory: ""
    },
    {
      name: "Haven Hall",
      region: "Gravelands",
      encyclopedia: "Place holder",
      notes: "",
      mines: "",
      refineries: "",
      buildingSites: "",
      trainingGrounds: "",
      vehicleFactory: ""
    },
    {
      name: "The Flutes",
      region: "Gravelands",
      encyclopedia: "Place holder",
      notes: "",
      mines: "",
      refineries: "",
      buildingSites: "",
      trainingGrounds: "",
      vehicleFactory: ""
    },
    {
      name: "Jagged Crag",
      region: "Gravelands",
      encyclopedia: "Place holder",
      notes: "",
      mines: "",
      refineries: "",
      buildingSites: "",
      trainingGrounds: "",
      vehicleFactory: ""
    },
    {
      name: "Hollow Hill",
      region: "Gravelands",
      encyclopedia: "Place holder",
      notes: "",
      mines: "",
      refineries: "",
      buildingSites: "",
      trainingGrounds: "",
      vehicleFactory: ""
    },
    {
      name: "The Crypts",
      region: "Gravelands",
      encyclopedia: "Place holder",
      notes: "",
      mines: "",
      refineries: "",
      buildingSites: "",
      trainingGrounds: "",
      vehicleFactory: ""
    },
    {
      name: "Shaded Pass",
      region: "Gravelands",
      encyclopedia: "Place holder",
      notes: "",
      mines: "",
      refineries: "",
      buildingSites: "",
      trainingGrounds: "",
      vehicleFactory: ""
    },
    {
      name: "Sanctuary",
      region: "Gravelands",
      encyclopedia: "Place holder",
      notes: "",
      mines: "",
      refineries: "",
      buildingSites: "",
      trainingGrounds: "",
      vehicleFactory: ""
    }
  ]